### PR TITLE
Updated install.sh to finally work

### PR DESCRIPTION
**Pull request by insomnia-creator**
The biggest issue was wget wasn't even installed on half the systems, wget does not come with our dear macs. I use npm and brew half the time so I never needed wget however there is a brew package for it.

Updated everything. If you find any error, point it out please. It works fine for me.

### CODE REVIEW

**Comment by insomnia-creator** [comment]
Closes #19

**Comment by Aayush9029** [comment]
I think a better idea would be using curl instead.

I think you can specify output using -o or something I'll look more into this later.


I forgot wget doesn't come with macOS out of the box 😅

**Comment by insomnia-creator** [comment]
Wget will be useful later as well... But curl is a good option yes... Since you were insisting on using wget...

I'll update the file with support for curl

**Comment by Aayush9029** [comment]
Sweet!

**Comment by insomnia-creator** [comment]
Don't merge this PR yet...

**Comment by insomnia-creator** [comment]
I'll see curl later, gonna go to sleep... Will update tomorrow.

**Comment by Aayush9029** [comment]
curl -LO 

Seems to work fine for me
Can you verify?

**Comment by insomnia-creator** [comment]
Right.

**Comment by insomnia-creator** [comment]
Closing this pull request as I will merge this with #23

**Pull request closed without merging**
