### PR TITLE
Refactored a ton of files.

### PR DESCRIPTION
**Pull request by erikbdev**
Hello!

In this pull request I refactored a ton of logic that to me seemed a bit redundant, there are still a couple more that I would like to refactor but I will probably work on that later. I removed the old AppKit stuff, like `Main.storyboard` and `AppDelegate.swift` in favor of the SwiftUI version of lifecycle.

I also improved App state by creating an `AppStateViewModel` which handles any shared data between views and publishes on data change across views.

There are some couple performance improvements and some ui improvement, such as a Preference Panel and we can add a general settings tab for any additional settings in the future.

Feel free to change anything you believe there should be change! :)

Screen Shot 2022-02-06 at 2 35 27 PM

Screen Shot 2022-02-06 at 2 33 38 PM

### CODE REVIEW

**Comment by Aayush9029** [comment]
Most of the stuff looks neat! Definitely liking the new changes!

**Comment by Aayush9029** [comment]
Will merge this, will be merging linted codebase as well!

**Comment by erikbdev** [comment]
Are there any features that you would still want to add in the future? I can possibly help out!

**Comment by Aayush9029** [comment]
> Are there any features that you would still want to add in the future? I can possibly help out!

if you’re up for it feel free to explore https://github.com/Aayush9029/NativeYoutube/tree/main/NativeYoutube/AVPlayer

This will eliminate the need for IINA to be installed just to play music!
*we could add VLC kit if AVPlayer isn’t enough. (networking wise)*

- - -

I was also thinking of adding URL schemes to play videos on the app by opening  

[nativeyoutube://video-id](nativeyoutube://video-id)

Which will act as a foundation for us to create safari extensions, raycast /Alfred extensions, terminal app and much more.

lmk what you think.

**Comment by erikbdev** [comment]
> if you’re up for it feel free to explore https://github.com/Aayush9029/NativeYoutube/tree/main/NativeYoutube/AVPlayer
> 
> This will eliminate the need for IINA to be installed just to play music! _we could add VLC kit if AVPlayer isn’t enough. (networking wise)_

I'll take a look and see what I can do about it. Most likely we will have to use VLCKit but I will try to see if I can do it without it.



> I was also thinking of adding URL schemes to play videos on the app by opening
> 
> nativeyoutube://video-id
> 
> Which will act as a foundation for us to create safari extensions, raycast /Alfred extensions, terminal app and much more.

I created a feature request for that  here: #58.

**Pull request merged**
