### PR TITLE
Final install.sh

### PR DESCRIPTION
**Pull request by insomnia-creator**
Thank you @nathom for suggesting the IF statement applications very much! This helps massively in lowering download/update speeds, I've added package checks as well and many more!

This is the final version of install.sh, (please tell what further can we do)

I've also updated my version to work with the DMG installer. 

Please suggest what can I do further

### CODE REVIEW

**Comment by Aayush9029** [comment]
Cyan is not sus. Cyan was doing wires.

**Comment by insomnia-creator** [comment]
Nooo but I saw him kill red and vent

**Comment by Aayush9029** [comment]
We can also add


xattr command, it gets rid of apple quarantine?

**Comment by insomnia-creator** [comment]
Will see.
Nvm figured it out.

**Pull request merged**
